# https://docs.github.com/actions

name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  npm-run:
    name: Node.js
    uses: YOURLS/.github/.github/workflows/nodejs.yml@main
    with:
      action-matrix: '["lint", "build"]'
